import type { NextPage } from "next";
import Head from "next/head";
import { Children, MouseEvent, useEffect, useState } from "react";
import styled from "styled-components";
import Bound from "../components/Bound";
import Text from "../components/Text";
import Avatar from "../components/Avatar";
import Button from "../components/Button";

interface Ipost {
  avatar: string;
  did: string;
  donation: string;
  post: string;
  time: string;
  location: string;
}

const SBound1 = styled(Bound)`
  position: fixed;
  right: 13.4rem;
  padding: 0;
  padding-top: 1.37rem;
  display: flex;
  flex-direction: column;
`;

const SText = styled(Text)`
  font-weight: medium;
`;

const SMain = styled.main`
  display: flex;
  justify-content: center;
`;

const SBox = styled.div`
  max-width: 57rem;
  width: 100%;
  display: flex;
  justify-content: space-between;
  margin: 1rem;
  margin-top: 3rem;
`;

const SBound = styled(Bound)`
  margin-top: 3rem;
  padding: 0;
`;

const SPost = styled.img`
  max-width: 25rem;
  width: 100%;
  border-radius: 1.25rem;
  /* padding-top: 1rem; */
`;

const SCont = styled.div`
  padding: 1rem;
  height: 2rem;
  background: ${({ theme }) => `${theme.donation}`};
  border-radius: 1rem;

  display: flex;
  justify-content: center;
  align-items: center;
`;

const SBox1 = styled.div`
  margin-right: 2rem;
`;

const SBox2 = styled.div`
  display: flex;
  ////in case of future problems
  width: inherit;
  justify-content: space-between;
  padding-bottom: 1rem;
`;

const SBox3 = styled.div`
  display: flex;
  flex-direction: column;
  padding-left: 1rem;
`;

const SBox4 = styled.div`
  display: flex;
  justify-content: space-between;
  width: inherit;
  padding: 3rem;
`;

const SAmount = styled(Text)`
  color: ${({ theme }) => `${theme.text2}`};
  font-weight: medium;
`;

const SText1 = styled(Text)`
  font-size: 0.875rem;
  font-weight: medium;
  color: ${({ theme }) => `${theme.text3}`};
`;

const SBox5 = styled.div`
  background: ${({ theme }) => `${theme.accent1}`};
  width: inherit;
  display: flex;
  height: 2.4rem;
  align-items: center;
  justify-content: space-between;
  padding: 0 1rem;
  border-radius: 1.25rem;
  position: relative;

  &:after {
    content: "";
    position: absolute;
    left: 0;
    top: -20px;
    width: 100%;
    height: inherit;
    background: inherit;
    z-index: -1;
  }
`;

const SLine = styled.div`
  border-top: ${({ theme }) => `2px solid ${theme.nav}`};
  width: inherit;
`;

const SBox6 = styled.div`
  display: flex;
  align-items: center;
`;

const Simg = styled.img`
  height: 0.83rem;
  width: 0.7rem;
  margin-right: 0.25rem;
`;

const SDonBox = styled.div`
display: flex;
width: inherit;
padding: .65rem 1.2rem;
`

const Simg1 = styled.img`
padding-right: 0.75rem;
`
const SButton = styled(Button)`
margin: 1.625rem 0 1rem 0;
`

const data = [
  {
    avatar: "/20200713.jpg",
    did: "0xc0ffee...d54979",
    donation: "500",
    post: "/20200715.jpg",
    time: "33 min",
    location: "Lagos, Nigeria",
  },
];

const Home: NextPage = () => {
  const [posts, setPosts] = useState<Ipost[]>();

  useEffect(() => {
    setPosts(data);
  }, []);

  return (
    <>
      <Head>
        <title>Enfvy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SMain>
        <SBox>
          <SBox1>
            <SText type="h4">Timeline</SText>
            <SBound maxWidth="36rem">
              {posts?.map((post) => (
                <>
                  <SBox4>
                    <Avatar
                      imgUrl={post.avatar}
                      height={"4rem"}
                      width={"4rem"}
                    />
                    <SBox3>
                      <SBox2>
                        <SText>{post.did}</SText>
                        <SCont>
                          <img src="/leaf.svg" />
                          <SAmount type="h6">{post.donation}</SAmount>
                        </SCont>
                      </SBox2>
                      <SPost src={post.post} />
                      <SBox5>
                        <SText1>{post.time}</SText1>
                        <SBox6>
                          <Simg src="/location.svg" />
                          <SText1>{post.location}</SText1>
                        </SBox6>
                      </SBox5>
                    </SBox3>
                  </SBox4>

                  <SLine></SLine>
                </>
              ))}
            </SBound>
          </SBox1>

          <SBound1 maxWidth="19rem" height="14rem">
            <SDonBox>
              <Simg1 src="/PooledFunds.svg" alt="" />
              <Text>Pooled Funds: 0</Text>
            </SDonBox>
            <SDonBox>
              <Simg1 src="/location.svg" alt="" />
              <Text>Events Completed: 0</Text>
            </SDonBox>
            <SDonBox>
              <Simg1 src="/leaf.svg" alt="" />
              <Text>Your Donation: 0</Text>
            </SDonBox>
            <SButton  func={()=>{}}>Connect wallet</SButton>
          </SBound1>
        </SBox>
      </SMain>
    </>
  );
};

export default Home;
